### ISSUE TITLE
How can you determine the Tekton version that is in IKS or OS

### ISSUE THREAD

**Issue by mjperrins** [ibm-garage-cloud/ibm-garage-tekton-tasks#10]
How can you determine the Tekton version that is in IKS or OS,

- [ ] can we update the README to make it clear how to determine the version
- [ ] Can we make it clear in the README what the steps are for using Tekton tasks with IKS + KNATIVE

**Comment by seansund** [comment]
Issue moved to [ibm-garage-cloud/planning #326](https://github.com/ibm-garage-cloud/planning/issues/326) via [**ZenHub**](https://www.zenhub.com/)
