### ISSUE TITLE
Tekton Health fails if package.json not updated

### ISSUE THREAD

**Issue by mjperrins** [ibm-garage-cloud/ibm-garage-tekton-tasks#11]
The tekton Task for Health is incorrectly assuming the app name is based on the `package.json` name rather than the repository name. The decision for `Jenkinsfile` was to base the deployment name based on the git repo name. This Task may need to be updated to validate that. 

```
    # Export project name, version, and build number to ./env-config

    npm run env | grep "^npm_package_name" | sed
    "s/npm_package_name/APP_NAME/g"  > ./env-config
command:
  - /bin/bash
image: '${inputs.params.js-image}'
name: setup
resources: {}
workingDir: '${inputs.resources.source.path}'
id: setup

```

**Comment by csantanapr** [comment]
From last time I looked at the jenkins file, the user needs to set BOTH the app name and version in a single place that’s package.json

**Comment by csantanapr** [comment]
I was told this was the reason the java apps also had package.json

**Comment by csantanapr** [comment]
having this info stored in a file package.json or foo.yaml is much better than a repository name as changing the file has less dependencies if the app name or version need to be change as oppose changing the repo name both the git hooks and runtime aspects need to be change.

**Comment by mjperrins** [comment]
The latest jenkins file retrieve the ingress to get the app url , so assuming a value from a package.json is not assumed to be valid , lets let @seansund way in on a comment , the approach for both flows should produce a reliable pipeline

**Comment by seansund** [comment]
For now, everything works off of the repo name. In a perfect world, the GitHub template generator would allow us to change the name in the package.json to match the repo name during the repo generation process. Then they would be guaranteed to match initially and the user would not be required to change the value in the package.json to prevent naming collisions.

**Comment by csantanapr** [comment]
I agree now everything is off repo name and it’s a step forward. 
But I would like to see an override option maybe a ConfigMap for the app?

**Comment by seansund** [comment]
Issue moved to [ibm-garage-cloud/planning #325](https://github.com/ibm-garage-cloud/planning/issues/325) via [**ZenHub**](https://www.zenhub.com/)
