### ISSUE TITLE
Add tekton Github and Gitlab Web hook triggers

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-cloud/ibm-garage-tekton-tasks#13]
Add tekton Github and Gitlab Web hook triggers

This will allow developer when setting the pipeline to configure git repo with a webhook, then pushing code to the repo will trigger the pipeline.

The `igc` command line then can automate this one time configuration setup with `igc pipeline --tekton`

**Comment by csantanapr** [comment]
This is possible now that the OpenShift Pipelines Operator v0.10.7 installs tekton controller v0.10.1 and triggers v0.2.1

```
oc describe pod tekton-pipelines-controller-cbbbb9b6-cnzbk -n openshift-pipelines | grep Image
    Image:         quay.io/openshift-pipeline/tektoncd-pipeline-controller:v0.10.1
```
```
oc describe pod tekton-triggers-controller-84766fbf76-zpggx -n openshift-pipelines | grep Image
    Image:         quay.io/openshift-pipeline/tektoncd-triggers-controller:v0.2.1
```

**Comment by seansund** [comment]
Issue moved to [ibm-garage-cloud/planning #323](https://github.com/ibm-garage-cloud/planning/issues/323) via [**ZenHub**](https://www.zenhub.com/)
